'use client'
import { Inter } from 'next/font/google'
import style from '../../style/home.module.css'
import nav from '../../style/nav.module.css'
import Menu from '../../components/Menu';
import './globals.css'
import { usePathname } from 'next/navigation';


const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  
let path = usePathname()
console.log(path)
  return (
    <html lang="en">

      <body className={inter.className}>
        <div className={style.board}>
       
            {path != "/"?<div className={nav.menubar}>
              <Menu />
            </div>:null}
          
          {children}
        </div>
        <link
          href="https://cdn.jsdelivr.net/npm/remixicon@4.1.0/fonts/remixicon.css"
          rel="stylesheet"
        />
        <script src="https://kit.fontawesome.com/1fde861766.js" crossorigin="anonymous"></script>
      </body>
    </html>
  )
}
